/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package conexaoBanco;

import java.sql.Connection;
import java.sql.SQLException;

public class App {

    public static void main(String[] args) throws SQLException {
        ConexaoSQLite conexaoSQLite = new ConexaoSQLite();
        Connection conexao = conexaoSQLite.conectar();
        
        //CriarTabela.criarTabelaUsuarios(conexao);
        
        //InserirUsuario.inserirUsuario(conexao, "Gustavo", "paulongo18Gmail.com");
        //InserirUsuario.inserirUsuario(conexao, "Leo", "seguiperdido@gmail.com");
        //InserirUsuario.inserirUsuario(conexao, "duda", "paodequeijo@gmail.com");
        //InserirUsuario.inserirUsuario(conexao, "Leo", "comenovinha@gmail.com");
        
        System.out.println(ListarUsuarios.listarUsuarios(conexao));
        
        AtualizarUsuarios.atualizarUsuario(conexao, 4, "LeonardoDicaprio", "comenavinha");
        
        System.out.println(ListarUsuarios.listarUsuarios(conexao));
        
        DeletarUsuario.deletarUsuario(conexao, 4);
    }
}
